'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        '''
        idea:
        brute force. two for loop. O(n^2)
        '''
        for i in range(len(t)):
            for j in range(len(s)):
                if t[i] != s[j]


    def findTheDifference(self, s, t):
        '''
        idea:
        sort string and compare each letter.
        '''
